config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'posts#index'
  devise_for :users

  resources :posts do
    get 'images', :on => :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    validates :image, presence: true
    validates :content, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  validates :username, presence: true
  has_many :comments, dependent: :destroy

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_attrs = [ :email, :username, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        post = Post.find(params[:post_id])
        @comment = post.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
    end
    
    private

    def comment_params
        params.require(:comment).permit(:comment)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    if params[:search] == nil
      @posts= Post.all.order(id: "DESC")
    elsif params[:search] == ''
      @posts= Post.all.order(id: "DESC")
    else
      @posts = Post.where("content LIKE ? ",'%' + params[:search] + '%').order(id: "DESC")
    end
  end

  def show
    if Post.find_by(id: params[:id])
      @post = Post.find(params[:id])
      @like = Like.new
      @comments = @post.comments
      @comment = @post.comments.build
    else
      @posts = Post.all.order(id: "DESC")
      redirect_to :action => "index"
    end
  end
  


  def images
    if params[:search] == nil
      @posts= Post.all.order(id: "DESC")
    elsif params[:search] == ''
      @posts= Post.all.order(id: "DESC")
    else
      @posts = Post.where("content LIKE ? ",'%' + params[:search] + '%').order(id: "DESC")
    end
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    if @post.save
      redirect_to :action => "index"
    else
      @posts = Post.all.order(id: "DESC")
      render :action => "index"
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user.id == post.user_id
      post.destroy
      redirect_to action: :index
    else
      redirect_to action: :index
    end
  end


  private
  def post_params
    params.require(:post).permit(:content,:image)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everyone's New Gear</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Everyone's New Gear . . .", root_path %></h1>
      <div class="header-list">
      <ul>
      <% if user_signed_in? %>
        <li>ログイン中: <%= current_user.username  %></li>
        <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
        <li><%= link_to "画像一覧", images_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete ,data: {confirm: "ログアウトしますか？"}%></li>
      <% else %>
        <li><%= link_to "画像一覧", images_posts_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
      <% end %>
      </ul>
      </div>
    </header>
    <div class="main">
      <%= yield %>
    </div>

    <footer>
      <p>© 2020 Everyone's New Gear... by nimuyohu</p>
    </footer>
  </body>
</html>

app/views/posts/images.html.erb
<%= link_to "一覧に戻る", posts_path %>
<h2>投稿を検索</h2>
<%= form_tag({controller:"posts",action:"images"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
<% end %>
<% @posts.each do |t| %>
    <%= link_to image_tag(t.image_url, size: "250x200"), post_path(t.id) %>
<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="posts-container">
    <h2 class="title">あなたの my new gear... を全世界に共有しよう</h2>
    <br>
    <% if user_signed_in? %>
    <div class="form">
        <h1>my new gear...する</h1>
        <% @post.errors.full_messages.each do |message| %>
                <div class="form-error">
                    <%= message %>
                </div>
            <% end %>
        <%= form_for @post do |f| %>
            <div class="field">
                <%= f.label :画像 %>
                <br>
                <%= f.file_field :image %>
                <p>※jpg/jpeg/gif/png形式のみ</p>
            </div>
            <div class="field">
                <%= f.label :content %>
                <%= f.text_area :content,:placeholder => "商品の説明" , :size => 140 %>
            </div>
                <%= f.submit "投稿する",class: "submit"%>
        <% end %>
        </div>
    <%end%>
    <br>
    <h3>投稿を検索</h3>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
        <%= text_field_tag :search,'',class: "search"%>
        <%= submit_tag '検索する'  %>
    <% end %>
    <% @posts.each do |t| %>
        <div class="post">
            <div class="main-box">
                <ul>
                    <h2>my new gear...</h2>
                    <li>
                        <%= link_to image_tag(t.image_url, size: "500x400"), post_path(t.id) %>
                    </li>
                    <li>
                        <%= t.content %>
                    </li>
                    <li>
                        投稿者：<%= link_to t.user.username, user_path(t.user.id) %>
                    </li>
                    <li>
                        <%= t.created_at.strftime("%Y/%m/%d　%H:%M:%S") %>
                    </li>
                    <% if user_signed_in? && current_user.id == t.user.id %>
                    <%= link_to '削除',post_path(t.id),method: :delete,data: {confirm: "削除しますか？"} %>
                    <% end %>
                    <h3>❤️<%= t.likes.count %></h3>
                </ul>             
            </div>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div class="show">
<h1>my new gear...</h1>
    <p>投稿者：<%= link_to @post.user.username, user_path(@post.user.id) %></p>
    <%= image_tag @post.image_url, size: "500x400" if @post.image? %>
    <p><%= @post.content %></>
    <p><%= @post.created_at %></p>
    <% if user_signed_in? && current_user.id == @post.user.id %>
        <%= link_to '削除',post_path(@post.id),method: :delete,data: {confirm: "削除しますか？"} %>
    <% end %>
    <h3>❤️<%= @post.likes.count %></h3>
    <% if user_signed_in? && current_user.already_liked?(@post) then %>
        <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
    <% elsif user_signed_in? && !(current_user.already_liked?(@post)) then %>
        <%= button_to 'いいね', post_likes_path(@post) %>
    <% end %>
</div>
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
    <li><%= user.username %></li>
<% end %>
<h2>
<%= link_to "一覧に戻る", posts_path %>
</h2>
<div class="comment-wrapper">
    <p>コメント一覧</p>
    <% @comments.each do |c| %>
        <div>
        >><%= c.user.username unless c.user.blank? %>
        <br>
        <%= c.comment %>
        </div>
        <br>
    <% end %>

    <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |f| %>
        <%= f.text_area :comment%>
        <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
        <% end %>
        <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="posts-container">
<p>名前 : <%= @user.username %></p>

<% if user_signed_in? && current_user.id == @user.id %>
    <%= link_to "ユーザー情報を編集する", edit_user_registration_path %>
    <br>
<% end %>
<br>
<h2><%= @user.username %>さんのmy new gear...一覧</h2>
<% @user.posts.each do |t| %>
    <div class="post">
        <div class="main-box">
                <ul>
                    <h2>my new gear...</h2>
                    <li>
                        <%= link_to image_tag(t.image_url, size: "500x400"), post_path(t.id) %>
                    </li>
                    <li>
                        <%= t.content %>
                    </li>
                    <li>
                        <p>投稿者：<%= t.user.username %></p>
                    </li>
                    <li>
                        <%= t.created_at.strftime("%Y/%m/%d　%H:%M:%S") %>
                    </li>
                    <% if user_signed_in? && current_user.id == t.user.id %>
                    <%= link_to '削除',post_path(t.id),method: :delete,data: {confirm: "削除しますか？"} %>
                    <% end %>
                    <h3>❤️<%= t.likes.count %></h3>
                    <% if user_signed_in? && current_user.already_liked?(t) then %>
                    <%= button_to 'いいねを取り消す', post_like_path(t), method: :delete %>
                    <% elsif user_signed_in? && !(current_user.already_liked?(t)) then %>
                        <%= button_to 'いいね', post_likes_path(t) %>
                    <% end %>
                </ul>             
        </div>
    </div>
<% end %>
</div>

<%= link_to "Tweet一覧に戻る", posts_path %>